### PR TITLE
example for compute energies with mpi

### PR DESCRIPTION
**Pull request by hainm**
you can merge this PR and check the script folder (with script + data for demo). change to your need.

### CODE REVIEW

**Comment by kmb413** [comment]
Cool, thanks. So in generating the parm7 file, am I supposed to solvate the box?

I've been doing this in tleap:

source leaprc.ff12SB
loadAmberParams frcmod.ionsjc_tip3p
mol = loadpdb 1aaj.pdb
saveamberparm mol 1aaj.parm7 inpcrd

**Comment by hainm** [comment]
no
- we compute energy in implicit solvent.
- you should always use 14SB versions (more detail below) instead of 12SB.

this should work:

`tleap`

``` python
source leaprc.ff14SBonlysc
m = loadpdb 1aaj.pdb
set default pbradii mbondi3
saveamberparm m 1aaj.parm7 1aaj.rst7
quit
```

Please note that we will use
-  `ff14SBonlysc` (not `ff14SB` since `ff14SB` is optimized for TIP3P water model).
- `mbondi3` radii set (vs mbondi2, bondi, ...)

and this is minimization input used in my folding paper: http://pubs.acs.org/doi/abs/10.1021/ja5032776

``` python
min.in
&cntrl
       imin = 1,
       maxcyc = 500,
       ncyc = 250,
       ntb = 0,
       igb = 8, 
       cut = 999.0
/
```

Let me know if you have other questions.

**Comment by kmb413** [comment]
These are the preliminary score files, where the rmsd is CA-rmsd between
decoy and the hydrogen-less crystal structure of 1aaj (with the N-terminal
2 residues removed). All calculations are done on the unaltered decoys in
the decoys.set2.init/1aaj directory.

**Comment by hainm** [comment]
Did you attach file to gmail when replying to github? This does not work. Can u send via email?

**Pull request merged**
